version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Attributify
  - birpc
  - bumpp
  - composables
  - iconify
  - jsqr
  - luby
  - nuxi
  - Nuxt
  - nuxtjs
  - ohash
  - pako
  - pinia
  - Positionals
  - qifi
  - QRCODE
  - Soliton
  - timeseries
  - unocss
  - vueuse
  - wechat
ignoreWords: []
import: []
